name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write   # potrzebne do działania cache
  cache: write     # pozwala na zapisywanie cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17 + Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Auto-approve if tests pass
        uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event_name == 'pull_request' && success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-reject if tests fail
        uses: mate-academy/auto-reject-action@v2
        if: ${{ github.event_name == 'pull_request' && failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
