name: Java CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Use a more general cache key based on OS and dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests=false verify

      - uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event.pull_request && success() }}
        with:
          github-token: ${{ github.token }}

      - uses: mate-academy/auto-reject-action@v2
        if: ${{ github.event.pull_request && failure() }}
        with:
          github-token: ${{ github.token }}
